
[package]
name = "pdf_derive"
version = "0.1.16"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian KÃ¶ln <sebk@rynx.org>"]
homepage = "https://github.com/pdf-rs"
repository = "https://github.com/pdf-rs/pdf_derive"
description = "helper for pdf-rs."
license = "MIT"

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[lib]
proc-macro = true
