[package]
name = "pdf"
version = "0.7.1"
authors = ["Erlend Langseth <3rlendhl@gmail.com>", "Sebastian KÃ¶ln <s3bk@protonmail.com>"]
repository = "https://github.com/pdf-rs"
readme = "../README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf"
edition = "2018"
description = "PDF reader"

[features]
mmap = ["memmap"]
dump = ["tempfile"]
threads = ["jpeg-decoder/default"]
standard-fonts = []

[dependencies]
pdf_derive = { version = "0.1.21", path = "../pdf_derive" }
snafu = "0.6.10"
num-traits = "0.2.14"
inflate = "0.4.5"
byteorder = "1.4.2"
itertools = "0.10.0"
ordermap = "0.4.2"
memmap = { version = "0.7.0", optional = true }
lzw = "0.10.0"
glob = "0.3.0"
chrono = "0.4.19"
once_cell = "1.5.2"
log = "0.4.14"
tempfile = { version = "3.2.0", optional = true }
md5 = "0.7"
jpeg-decoder = { version = "0.1", default-features = false }
aes = "0.6.0"
block-modes = "0.7.0"
stringprep = "0.1.2"
sha2 = "0.9.2"

[lib]
doctest = false
