[package]
name = "pdf"
version = "0.7.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian KÃ¶ln <sebk@rynx.org>"]
repository = "https://github.com/pdf-rs"
readme = "README.md"
keywords = ["pdf"]
license = "MIT"
documentation = "https://docs.rs/pdf"
edition = "2018"
description = """
Read, alter and write PDF files.
(Crate that previously resided here moved to pdf-canvas)
"""

features = ["unstable"]

[dependencies.pdf_derive]
path = "../pdf_derive"
[dependencies.encoding]
path = "../encoding"

[dependencies]
snafu = "0.4"
isatty = "0.1"
num-traits = "0.1.36"
inflate = "0.4.5"
ansi_term = "0.9.0"
byteorder = "1.0.0"
itertools = "0.6.0"
ordermap = "0.2.9"
memmap = "0.5.2"
lzw = "0.10.0"
tuple = "0.4.0"
glob = "0.2.11"
chrono = "0.4.0"
once_cell = "0.2"
log = "*"
tempfile = "*"
md5 = "0.6"

[lib]
doctest = false

