[package]
name = "view"
version = "0.1.0"
authors = ["Sebastian KÃ¶ln <sebk@rynx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = { path = "../pdf" }
font = { path = "../font" }
pathfinder_geometry = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_content = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_canvas = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_renderer = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_gl = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_gpu = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
pathfinder_export = { git = "https://github.com/s3bk/pathfinder/", branch="local-skribo" }
euclid = "0.19"
log = "*"
env_logger = "*"
gl = "0.6"
sdl2 = "0.32"
sdl2-sys = "0.32"
freetype = "^0.4.1"

[dependencies.font-kit]
git = "https://github.com/pcwalton/font-kit/"

[dependencies.skribo]
git = "https://github.com/s3bk/skribo"

[[bin]]
name = "pdf_view"

[[bin]]
name = "pdf2svg"
