[package]
name = "text"
version = "0.1.0"
authors = ["Erlend Hofstad Langseth <3rlendhl@gmail.com>", "Sebastian KÃ¶ln <sebk@rynx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = { path = "../../pdf" }
